### ISSUE TITLE
Add meal breaks to grid

### ISSUE THREAD

**Issue by martian-a** [geeksoflondon/grid4rails#1]
(18:05:21) kevinprince: tommorris: the grid isnt outputting right btw as the lunch etc are missing
(18:05:34) kevinprince: might been easier to just create "talks" for those slots
(18:07:06) tommorris: just note it down and I'll fix it
(18:07:49) tommorris: eventually, we'll just have one gigantic object graph that'll get created for everything.
(18:08:00) tommorris: including lunch and stuff

**Comment by kevinprince** [comment]
Me and Leeky have fixed this.
