### ISSUE TITLE
Test Timezone Support

### ISSUE THREAD

**Issue by leeky** [geeksoflondon/grid4rails#101]
BCL9 falls on the BST/GMT changeover, so we need to test that Griddy will show the correct times for sessions.

**Comment by martian-a** [comment]
When it's configured for those dates, the timeslots certainly take the clock change into account.  Other than changing the time on a local instance and seeing what happens, do you have any better suggestions for how we might test this?

**Comment by martian-a** [comment]
I've created an instance for the dates of BCL9 that handles the clock change as far as getting the times right in the schedule.  I'm reluctant to change the date and time on my laptop again to fake the clock change on a local instance given that that's caused me some problems, I'd rather leave it at that.  As far as I can tell, it should handle the change.
