### ISSUE TITLE
Changes to talk (edit) aren't saved

### ISSUE THREAD

**Issue by martian-a** [geeksoflondon/grid4rails#11]
To reproduce:
1. I find an existing talk and click on the edit option
2. I change the title, speaker and/or description data
3. I click on the "Update talk" button
4. I am redirected to the "show" view of that talk which includes a message telling me that the talk has been successfully updated.

Expected result:
- to see the that changes that I've just made have been saved, as evidenced by the data in the view.

Actual result:
- no changes has been saved.  The data is the same as it was before I edited it.

**Comment by kevinprince** [comment]
Fixed.

**Comment by martian-a** [comment]
Thanks.
