### ISSUE TITLE
Now view - style Earlier and Later 

### ISSUE THREAD

**Issue by morena** [geeksoflondon/grid4rails#16]
Has been started on shiny, needs improving on both Simple and Shiny

**Comment by morena** [comment]
I'm on it

**Comment by morena** [comment]
I don't think we need to improve the style of the Later and Earlier buttons. I think instead we should position them around the "Now" heading.

Can anybody do that in the backend? At least as a test...

**Comment by kevinprince** [comment]
This is what im seeing, not sure what you want changing:

http://postimage.org/image/19vjk2fqc/
http://postimage.org/image/19w521y5g/
http://postimage.org/image/19wjxw2lg/

**Comment by markstickley** [comment]
I think morena is thinking it should be more like

<< Earlier NOW Later >>

Doing this would be challenging while keeping the markup semantic so I'd recommend leaving as it is for now at least. Maybe something to revisit in the future.

Morena: please close if you agree.
