### ISSUE TITLE
Everywhere - Style Footer

### ISSUE THREAD

**Issue by morena** [geeksoflondon/grid4rails#18]

**Comment by markstickley** [comment]
Do we have a design or style guide to work from or are we just ad-libbing? If the latter I'll probably let better qualified folk work on this sort of ticket!

**Comment by morena** [comment]
We don't have a design for the footer. I showed it to my designer colleague and he suggested we make the URLs smaller, left aligned and with a | separator in between. I can give it a go and we can see if we like it

**Comment by morena** [comment]
Done it, maybe the pipe needs to be lighter, let me know what you guys think

**Comment by markstickley** [comment]
Looks great! I would make the colour the same as the pipes in the mode switcher in the top right.

**Comment by martian-a** [comment]
Changed colour as per Mark's suggestion.  Also added server-side check for version so pipes don't show when options are stacked on top of each other, rather than inline.
