### ISSUE TITLE
Everywhere - make room clickable

### ISSUE THREAD

**Issue by morena** [geeksoflondon/grid4rails#19]

**Comment by kevinprince** [comment]
Needs a bit more context. What do we want to show?

Also not sure if this is needed.

**Comment by martian-a** [comment]
Running order in that room.

**Comment by kevinprince** [comment]
Ok cool, will sort.

**Comment by martian-a** [comment]
Room view could include information on:
- location, such as, 3rd floor, and directions to there from, say, the main entrance, welcome talk room or lift
- facilities, eg. whiteboard but no projector
- sleep suitability?
- running order in that room, esp. now and next
- when/if we have check-in, who's in there?
