### ISSUE TITLE
Schedule talk - get rid of radio buttons and actions fieldset

### ISSUE THREAD

**Issue by markstickley** [geeksoflondon/grid4rails#34]
Just a suggested improvement:

Since there's already an "Add here" button actually within the empty slot, I don't think there's a need for a radio button to be selected. (It also currently errors if you click "Add here" without selecting the radio button.

The "Submit" button at the bottom is kind of redundant and not obvious that it's even there unless you scroll all the way down. The cancel button is useful and so I'd suggest that every "Add here" button has a Cancel button underneath it.

**Comment by kevinprince** [comment]
Done.
