### ISSUE TITLE
More Grey!

### ISSUE THREAD

**Issue by kevinprince** [geeksoflondon/grid4rails#35]
Can we make the the color scheme grey?

Would make it easier for each event etc.

**Comment by martian-a** [comment]
Implemented with themes. Grey theme is named "default".  Other themes include "mediacity" (red), "bcl9" (orange-ish), "blue" (pretty much the original colour scheme).  To switch themes, change the value of the new global variable, named "theme" in app/helpers/application_helper.rb.
