### ISSUE TITLE
Add to google analytics

### ISSUE THREAD

**Issue by martian-a** [geeksoflondon/grid4rails#51]
Add in code for google analytics.  Need to be able to differentiate between versions.

**Comment by tommorris** [comment]
Not sure about this. At BarCamp, we should probably collectively care about privacy of attendees. Although the data on the site is public, we shouldn't be giving data about our attendees to Google: some people may object greatly to having their details shared with Google and potentially allowing Google to link details of the identity they have given Google with that they are giving us. With OpenID/OAuth authentication, they have some choice what services they want to use to authenticate, but with Google Analytics, they don't.

It also introduces a non-free dependency which might prevent communities which are _more_ dedicated to open source principles from using Griddy for their events (think of Apache or Ogg Vorbis or Debian or Wikimedia etc.).

Instead, can I suggest we use [RailStat](http://www.railstat.com/) or possibly [Piwik](http://piwik.org/)?
