### ISSUE TITLE
Add speaker attribute to talks table

### ISSUE THREAD

**Issue by martian-a** [geeksoflondon/grid4rails#7]
Free-text (string) optional field for the talk creator to include some identifying info, if they wish, for example:
- @sheilaellen
- Evil Overlords, Inc.
- Calvin & Hobbes

**Comment by kevinprince** [comment]
Fixed at commit 

https://github.com/geeksoflondon/grid4rails/commit/58ca34d04868b9bab66489e59039d1b3ccc2d252
