### ISSUE TITLE
We need to decide on a license

### ISSUE THREAD

**Issue by tommorris** [geeksoflondon/grid4rails#76]
When we started working on Griddy, we put off deciding on a license.

I'm going to suggest that we should go with the **[Affero General Public License v. 3.0](http://www.gnu.org/licenses/agpl-3.0.html)**. It is a free software license specifically designed for web apps. It is used by a variety of web apps including StatusNet, OTRS, CiviCRM, and [many others](http://en.wikipedia.org/wiki/Affero_General_Public_License#Example_of_web_applications_under_AGPL).

The AGPL is functionally similar for web apps as the GPL is for desktop and server apps. Under the AGPL, others have all of Stallman's four freedoms, and have to share modifications made (like GPL does for desktop apps and Creative Commons Attribution-ShareAlike does for creative works like text and images).

If we can get consensus on using the AGPL, we can then modify the README and include a LICENSE.txt file.

If there isn't consensus on using the AGPL, we'll close this issue and decide on another license.

Any objections?

**Comment by cbetta** [comment]
I have no idea on  all this stuff so as long as stallman is happy I am

**Comment by tommorris** [comment]
cbetta: can I take that as a "so long as everyone else comes to a sane, consensual decision, I'll go with whatever"? ;-)

**Comment by cbetta** [comment]
Yeah. Although I think my beer-license is still a viable option too.

**Comment by martian-a** [comment]
Good with me too.

**Comment by kevinprince** [comment]
Beer sounds good. But AGPL also fine. 

As long as I dont get a bill for laywers.

**Comment by leeky** [comment]
Sounds good here!

**Comment by markstickley** [comment]
Sounds A-OK to me :)

**Comment by tommorris** [comment]
Morena has sent me an email confirming she is okay with the AGPL.

I'll sort the licensing out shortly.

**Comment by tommorris** [comment]
All done. We now have a license in the README and a LICENSE file containing the full text of the license.
