### ISSUE TITLE
When assigning a talk to a slot, the previously created talk is moved instead

### ISSUE THREAD

**Issue by martian-a** [geeksoflondon/grid4rails#77]
To reproduce: 
- create a new talk (T1)
- specify which slot you would like T1 assigned to
- create another new talk (T2)
- specify which slot you would like T2 assigned to

Instead of the newest talk (T2) being assigned to the specified slot.  T1 moves from it's prior slot to the spot specified for T2.  (Obviously, unless the grid is completely new when you try this, it'll happen with T1 too.)

T2 can be found on the Unscheduled Talks page.

**Comment by kevinprince** [comment]
now working on this

**Comment by kevinprince** [comment]
Fixed.
