### ISSUE TITLE
Hacked forms allow talks in already allocated slot.

### ISSUE THREAD

**Issue by leeky** [geeksoflondon/grid4rails#85]
If you make form fields writable in Web Developer Toolbar, you can change the ID of the slot to allocate a talk to.

This means you can allocate a talk to a previous assigned slot. The original talk then appears under "unscheduled talks"

**Comment by kevinprince** [comment]
This a general flaw with hidden fields and their is not much we can do to prevent this.

**Comment by kevinprince** [comment]
Also we are fixing other part of this bug :)

**Comment by martian-a** [comment]
Hoping I _have_ managed to prevent this. Leeky, can you try again, please?

**Comment by leeky** [comment]
I've just overwritten an existing talk with "Evil", so still seems to be broken.

**Comment by martian-a** [comment]
My bad.  Didn't expect you to pick up the message so quickly!  Heroku now updated with the fix.

**Comment by martian-a** [comment]
I believe this to be fixed now.
